name: .NET CI
on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Restore Packages
      run: nuget restore UniClubManagementSystem/UniClubManagementSystem/UniClubManagementSystem.csproj -SolutionDirectory UniClubManagementSystem/UniClubManagementSystem
      
    - name: Build
      run: msbuild UniClubManagementSystem/UniClubManagementSystem/UniClubManagementSystem.csproj /p:Configuration=Release

